apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kelvinskell/k8s-manifests.git
    targetRevision: HEAD
    path: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
